/*
 * motor.c
 *
 *  Created on: Dec 16, 2020
 *      Author: arahm
 */


#include "motor.h"

void MOTOR_init(void)
{
	SET_BIT(INPUT1_DDR,INPUT1);
	SET_BIT(INPUT2_DDR,INPUT2);
	SET_BIT(ENABLE_DDR,ENABLE);
	CLEAR_BIT(INPUT1_PORT,INPUT1);
	CLEAR_BIT(INPUT2_PORT,INPUT2);
	CLEAR_BIT(ENABLE_PORT,ENABLE);
}

void MOTOR_runCW(void)
{
	SET_BIT(INPUT1_PORT,INPUT1);
	CLEAR_BIT(INPUT2_PORT,INPUT2);
	SET_BIT(ENABLE_PORT,ENABLE);
}

void MOTOR_runACW(void)
{
	CLEAR_BIT(INPUT1_PORT,INPUT1);
	SET_BIT(INPUT2_PORT,INPUT2);
	SET_BIT(ENABLE_PORT,ENABLE);
}

void MOTOR_reverse(void)
{
	TOGGLE_BIT(INPUT1_PORT,INPUT1);
	TOGGLE_BIT(INPUT2_PORT,INPUT2);
	SET_BIT(ENABLE_PORT,ENABLE);
}

void MOTOR_stop(void)
{
	CLEAR_BIT(INPUT1_PORT,INPUT1);
	CLEAR_BIT(INPUT2_PORT,INPUT2);
	CLEAR_BIT(ENABLE_PORT,ENABLE);
}

